### ISSUE TITLE
try.goodtables.io returns API error

### ISSUE THREAD

**Issue by schlos** [okfn/tabular-validator-web#80] opened 2018-05-18 21:29 UTC
When file is submitted for testing, I get this error:
Can't create a job on API. Reason: "Error: Network Error"

**Comment by amercader** [comment] 2018-05-19 20:31
Hi @schlos thanks for reaching out. It is currently working for me, is it still failing for you? is it a particular file or link?

**Comment by schlos** [comment] 2018-05-31 10:02
Hi @amercader I can still reproduce issue, see screenshot:
https://qsnapnet.com/snaps/zm4r83458bqhbyb

I used upload file functionality for validation, file attached here:
https://app.box.com/s/c6pqi8bz5fzzfzyitp8brvswiifbckod

**Comment by amercader** [comment] 2018-05-31 11:31
Thanks @schlos, I can reproduce it with this file as well. The server is returning a 413 Entity Too Large error. That gives a good clue, we'll investigate a bit more.

**Comment by amercader** [comment] 2018-06-25 09:02
Hi @schlos the issue should be fixed now, it was a misconfiguration on our side.

Using the test file you provided validation won't work because of the `txt` extension:

https://try.goodtables.io/?apiJobId=dc8e04b0-7855-11e8-a96c-0a580a240208

If you change it to `.csv` you'll get actual validation errors:

https://try.goodtables.io/?apiJobId=07f17c7e-7856-11e8-92fe-0a580a240208

**Closed as completed by amercader** 2018-06-25 09:02 UTC
